### ISSUE TITLE
What additional topics should we discuss at our first working meeting?

### ISSUE THREAD

**Issue by jeffwired** [USEPA/EPA_OMEGA_Model#2]
Our first OMEGA 2 working session is scheduled for April 24th.  We should discuss overall program architecture as one topic.  What additional topics should we discuss to answer any questions and concerns from the team?

**Comment by danbarba** [comment]
I'd like to see a detailed 3-6 month plan developed with actions, names, and dates.

**Comment by jeffwired** [comment]
We need to discuss this recurring meeting schedule as most of the team is out on Fridays.

**Comment by kevinanewman** [comment]
I'd mostly like to start by doing the OMEGA 1 teardown and see what kinds of inputs and processes we need to handle, then once we (I) have a better idea what we're up against then maybe we will have enough information to starting figuring out how long things might take

**Comment by jeffwired** [comment]
> I'd mostly like to start by doing the OMEGA 1 teardown and see what kinds of inputs and processes we need to handle, then once we (I) have a better idea what we're up against then maybe we will have enough information to starting figuring out how long things might take

Along with looking at OMEGA 1, we need to discuss what tasks should remain offline.
