### ISSUE TITLE
Prebuild technology packages or decision trees?

### ISSUE THREAD

**Issue by jeffwired** [USEPA/EPA_OMEGA_Model#3]
As we discussed in our April 24, 2019 meeting regarding the Architecture of OMEGA 2, an important decision to be made is the method of sequentially applying technologies to vehicles for GHG improvement.

The current OMEGA method prebuilds and ranks a complete set of technology packages for each vehicle type based on SME engineering judgement.

The current DSE method uses technology information (cost, effectiveness, etc.) as inputs to the core process and uses "decision trees" to apply technology.

As we have experience using both methods, please respond to this thread with Pros and Cons (along with any questions or comments) for each methodology as thought starters for future group discussion. 

Thank you!

**Comment by kevinanewman** [comment]
I don't really know but it seems like anything you do in pre-processing probably speeds up the actual running, although ideally the pre-processing is automated so that it's easier to do...

I don't know if it's possible to have the model do a bunch of pre-processing the first time it runs then use those results for subsequent runs as long as the source data hasn't been modified, maybe split the difference.

**Comment by jbrownEPA** [comment]
We talked a small bit at the off-site about how one of the requirements of this project is to have inputs as close to 'raw' as possible. Performing pre-processing on inputs before they hit the model seems like it doesn't meet this goal.

This is not to say that a lot of pre-processors we currently have developed (either as part of the current OMEGA1 'suite', or something that happens offline) would not be useful, they are likely something that would need to be included as part of the OMEGA2 functionality. I could imagine an architecture where each 'raw' data input structure also includes its own pre-preprocessing or setup algorithms that run when that data structure is pulled in.

To @kevinanewman's point, I also think caching may be valuable here (as potentially in many other places in the architecture). It is certainly something that is _possible_, we will have to think about whether the increase in upfront design is worth it for the initial version of OMEGA2.

**Comment by kevinanewman** [comment]
In our meeting yesterday there was a pretty detailed walk-through of the current OMEGA process, it seems like it may be difficult and/or impossible to go from "raw" to "usable" without some human intervention (creating the starting fleet (formerly called "baseline" fleet but not actually renamed yet...)) so it may be that not all inputs are automatable.

However, there may be several options for the technology ranking and other steps that happen after the fleet definition so we will still have some decisions to make as to whether to do those live, or to cache them or whatever.
