### ISSUE TITLE
Any Topics, Comments, or Questions for our April 26, meeting?

### ISSUE THREAD

**Issue by jeffwired** [USEPA/EPA_OMEGA_Model#4]
Please add any Topics, Comments, or Questions to this thread for discussion at our April 26, 2019 meeting.

Thank you.

**Comment by molechiw** [comment]
Please plan on taking a few minutes to review program timing and deliverables.

**Comment by kbolon** [comment]
I have two possible topics - 
1) Continue the laying of the groundwork for future meetings by reveiwing existing compliance models: wrap up OMEGA1 and dive into CAFE/DSE or
2) Skip ahead to high-level discussion of program architecture. In particular, I think it would help us to lay-out the differences/implications of a present --> future (tech pathways approach) vs a future --> present (back-casting approach). That probably doesn't make sense from my description, but at some point early in this process we need to go over the fundamental flow and objective functions of the model.

**Comment by jeffwired** [comment]
> Please plan on taking a few minutes to review program timing and deliverables.

Here is the current timeline:
[OMEGA 2 Project Timeline.pdf](https://github.com/USEPA/EPA_OMEGA_Model/files/3117075/OMEGA.2.Project.Timeline.pdf)

**Comment by anthonyneam** [comment]
What do to with Friday meetings since many team member are out every other week?

**Comment by kbolon** [comment]
At yesterday's meeting, we decided to cancel every other Friday's meeting. So we will meet tomorrow, but not the following week.

**Comment by anthonyneam** [comment]
My CDO is tomorrow, and I have things planned on my CDO's going forward so I will not be at Friday meetings.

**Comment by kbolon** [comment]
It seems like a situation where there are no perfect answers, so we'll need to pick the next-best scheduling option. The people who have alternating Friday CDO's are Jarrod, Kevin N., Jeff, and Anthony. Since three of those 4 are working this Friday, we'll probably need to stick with that, unless we decide to give up on Fridays altogether.
