### ISSUE TITLE
Create 'production_constraints.csv' input file, and apply min, max constraints to producer share choices

### ISSUE THREAD

**Issue by kbolon** [USEPA/EPA_OMEGA_Model#47]
For now, this will only be used to specify the limits of BEV shares within the hauling and non-hauling classes (i.e. the relative, not absolute share).  In the future, we may want to rethink this in order to apply a universal GWh constraint. 

The inputs might look like

2021     {'Hauling.BEV': 0.0, 'NonHauling.BEV': 0.0}   {'Hauling.BEV': 0.07, 'NonHauling.BEV': 0.04}
2022     {'Hauling.BEV': 0.03, 'NonHauling.BEV': 0.01}   {'Hauling.BEV': 0.07, 'NonHauling.BEV': 0.04}

![3-24-2021 11-27-32 AM](https://user-images.githubusercontent.com/47565085/112337079-fdbc7680-8c93-11eb-8a66-5d8cdb404b88.png)

**Comment by kevinanewman** [comment]
done, but need to implement code to use the constraints
