### ISSUE TITLE
Add properties to 'required_zev_share.csv' inputs and class, and apply as constraints to producer decision choice set

### ISSUE THREAD

**Issue by kbolon** [USEPA/EPA_OMEGA_Model#48]
These policy requirements are applied as a minimum floor constraint on producer decisions, in addition to the constraints specified in the 'production_constraints' inputs.  Constraints are applied at the 'reg_class_id' level. However, that's probably not easy to implement at this time, given that the producer choices for BEV share are generated at the market class level now.  So for now either:
1) (preferred) implement at the overall level (so allow an 'all' setting for the 'reg_class_id'?
2) implement at the market class level (consistent with how producer choice sets are currently generated)

![3-24-2021 11-51-59 AM](https://user-images.githubusercontent.com/47565085/112342169-6279d000-8c98-11eb-89e6-86d5848b57f7.png)

**Comment by kevinanewman** [comment]
done, but by market class for now
