### ISSUE TITLE
Level of Detail in Compliance Modeling

### ISSUE THREAD

**Issue by kevinanewman** [USEPA/EPA_OMEGA_Model#6]
Currently, we track and define very specific low-level technologies for every vehicle make and model, such as DOHC, VVT, LUBE1, etc.

Some of these technologies are either not directly modeled or are only modeled in combination, for example in ALPHA simulations.

This leads to a lot of bookkeeping and may create the appearance of false precision or false accuracy.

We should discuss the appropriate level of detail required for compliance modeling as possibly being distinct from the level of detail required to determine tech effectiveness and/or tech costs.

If we keep the current level of detail for compliance modeling it should be a conscious decision as opposed to just doing things the way we always have or others have.

We should also have this discussion as regards vehicle types and definitions.  If we can somehow determine compliance at a slightly higher level of abstraction then we can avoid pitfalls like assuming specific vehicle makes and models will continue to exist in perpetuity (when we might already know they won't!) and/or that new vehicle makes and models will not appear during the compliance years (when they almost assuredly will).  This might be similar to the approach we have taken with transmission grouping (TRX11, TRX12 etc) where we abstract away some of the detail but maintain overall model accuracy.

**Comment by jeffwired** [comment]
Back in 2008 when the OMEGA model was first conceived, these technologies were being added to vehicles individually in production and OMEGA used this trend as the main technology paths for engine.
