### ISSUE TITLE
Any Topics, Comments, or Questions for our April 29, meeting?

### ISSUE THREAD

**Issue by jeffwired** [USEPA/EPA_OMEGA_Model#7]
Please add any Topics, Comments, or Questions to this thread for discussion at our April 29, 2019 meeting.

Thank you.

**Comment by jchbrown** [comment]
As discussed on the 26th, we should probably start working on a draft to Bill (et. al) regarding modeling options and what that means for what we can and cannot do for a near-term rulemaking.
